replicaCount: 1

image:
  repository: nspccdev/neo-go
  pullPolicy: IfNotPresent
  tag: "0.106.0"

network: "mainnet" # mainnet or testnet
syncMode: "full" # full or archive

node:
  maxPeers: 100
  p2pPort: 10333
  rpcPort: 10332
  prometheusPort: 2112

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "4"
    memory: "8Gi"

persistence:
  enabled: true
  size: 200Gi # Increase to 2Ti for archive
  storageClass: "gp3" # Or premium-rwo for GCP

service:
  type: ClusterIP
  annotations: {}
