replicaCount: 1

image:
  repository: neo-project/neo-cli
  pullPolicy: IfNotPresent
  tag: "3.7.4"

network: "mainnet"

node:
  p2pPort: 10333
  rpcPort: 10332

resources:
  requests:
    cpu: "2"
    memory: "6Gi"
  limits:
    cpu: "4"
    memory: "12Gi"

persistence:
  enabled: true
  size: 200Gi
  storageClass: "gp3"

service:
  type: ClusterIP
