apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neo-go.fullname" . }}-config
data:
  protocol.mainnet.yml: |
    ProtocolConfiguration:
      Magic: 860833102
      MaxTraceableBlocks: 2102400
      InitialGasDistribution: 52000000
      MaxTransactionsPerBlock: 512
      MaxValidUntilBlockIncrement: 5760
      SeedList:
        - seed1.neo.org:10333
        - seed2.neo.org:10333
        - seed3.neo.org:10333
        - seed4.neo.org:10333
        - seed5.neo.org:10333
    ApplicationConfiguration:
      DataDirectoryPath: "/data"
      P2P:
        Port: {{ .Values.node.p2pPort }}
        MaxPeers: {{ .Values.node.maxPeers }}
      RPC:
        Enabled: true
        Port: {{ .Values.node.rpcPort }}
        MaxGasInvoke: 10
      Prometheus:
        Enabled: true
        Port: {{ .Values.node.prometheusPort }}
