apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo-go.fullname" . }}
  labels:
    app: neo-go
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.node.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.node.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.node.prometheusPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: neo-go
